package main

import (
	"piscine"
	"fmt"
)


func main() {
	fmt.Println("6 x 4")
	piscine.QuadA(6,4) 
	fmt.Println("")
	piscine.QuadB(6,4)
	fmt.Println("") 
	piscine.QuadC(6,4) 
	fmt.Println("")
	piscine.QuadD(6,4)
	fmt.Println("")
	piscine.QuadE(6,4)
	fmt.Println("")

	fmt.Println("1 x 1")
	piscine.QuadA(1,1) 
	fmt.Println("")
	piscine.QuadB(1,1)
	fmt.Println("") 
	piscine.QuadC(1,1) 
	fmt.Println("")
	piscine.QuadD(1,1)
	fmt.Println("")
	piscine.QuadE(1,1)
	fmt.Println("")

	fmt.Println("2 x 1")
	piscine.QuadA(2,1) 
	fmt.Println("")
	piscine.QuadB(2,1)
	fmt.Println("") 
	piscine.QuadC(2,1) 
	fmt.Println("")
	piscine.QuadD(2,1)
	fmt.Println("")
	piscine.QuadE(2,1)
	fmt.Println("")

	fmt.Println("1 x 2")
	piscine.QuadA(1,2) 
	fmt.Println("")
	piscine.QuadB(1,2)
	fmt.Println("") 
	piscine.QuadC(1,2) 
	fmt.Println("")
	piscine.QuadD(1,2)
	fmt.Println("")
	piscine.QuadE(1,2)
	fmt.Println("")

	fmt.Println("2 x 2")
	piscine.QuadA(2,2) 
	fmt.Println("")
	piscine.QuadB(2,2)
	fmt.Println("") 
	piscine.QuadC(2,2) 
	fmt.Println("")
	piscine.QuadD(2,2)
	fmt.Println("")
	piscine.QuadE(2,2)
	fmt.Println("")

	fmt.Println("5 x 1")
	piscine.QuadA(5,1) 
	fmt.Println("")
	piscine.QuadB(5,1)
	fmt.Println("") 
	piscine.QuadC(5,1) 
	fmt.Println("")
	piscine.QuadD(5,1)
	fmt.Println("")
	piscine.QuadE(5,1)
	fmt.Println("")

	fmt.Println("1 x 5")
	piscine.QuadA(1,5) 
	fmt.Println("")
	piscine.QuadB(1,5)
	fmt.Println("") 
	piscine.QuadC(1,5) 
	fmt.Println("")
	piscine.QuadD(1,5)
	fmt.Println("")
	piscine.QuadE(1,5)
	fmt.Println("")

	fmt.Println("-3 x 5")
	piscine.QuadA(-3,5) 
	fmt.Println("")
	piscine.QuadB(-3,5)
	fmt.Println("") 
	piscine.QuadC(-3,5) 
	fmt.Println("")
	piscine.QuadD(-3,5)
	fmt.Println("")
	piscine.QuadE(-3,5)
	fmt.Println("")

	fmt.Println("5 x 0")
	piscine.QuadA(5,0) 
	fmt.Println("")
	piscine.QuadB(5,0)
	fmt.Println("") 
	piscine.QuadC(5,0) 
	fmt.Println("")
	piscine.QuadD(5,0)
	fmt.Println("")
	piscine.QuadE(5,0)
	fmt.Println("")
}
